import KoreanLunarCalendar from 'korean-lunar-calendar';

/**
 * 일주(日柱) calculation - Heavenly Stem + Earthly Branch for a given date.
 * Uses korean-lunar-calendar's validated 만세력/gapja calculation.
 */

// 천간 (Heavenly Stems)
export const CHEONGAN = ['갑', '을', '병', '정', '무', '기', '경', '신', '임', '계'];
export const CHEONGAN_HANJA = ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸'];

// 지지 (Earthly Branches)
export const JIJI = ['자', '축', '인', '묘', '진', '사', '오', '미', '신', '유', '술', '해'];
export const JIJI_HANJA = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];

// 오행 (Five Elements) mapping for 천간
export const CHEONGAN_OHAENG = {
  갑: '목', 을: '목',
  병: '화', 정: '화',
  무: '토', 기: '토',
  경: '금', 신: '금',
  임: '수', 계: '수'
};

// 오행 mapping for 지지
export const JIJI_OHAENG = {
  자: '수', 축: '토',
  인: '목', 묘: '목',
  진: '토', 사: '화',
  오: '화', 미: '토',
  신: '금', 유: '금',
  술: '토', 해: '수'
};

// 오행 한자 이름
const OHAENG_NAMES = {
  목: '목(木)',
  화: '화(火)',
  토: '토(土)',
  금: '금(金)',
  수: '수(水)'
};

export function calculateIlju(year, month, day) {
  const calendar = new KoreanLunarCalendar();
  const valid = calendar.setSolarDate(year, month, day);

  if (!valid) {
    throw new Error('Invalid solar date for ilju calculation');
  }

  const gapja = calendar.getKoreanGapja();
  const dayText = gapja.day.replace('일', ''); // e.g. "경진일" -> "경진"
  const cheongan = dayText[0];
  const jiji = dayText[1];

  const cheonganIndex = CHEONGAN.indexOf(cheongan);
  const jijiIndex = JIJI.indexOf(jiji);

  if (cheonganIndex === -1 || jijiIndex === -1) {
    throw new Error(`Failed to parse ilju from gapja day: ${gapja.day}`);
  }

  return {
    cheongan,
    jiji,
    cheonganHanja: CHEONGAN_HANJA[cheonganIndex],
    jijiHanja: JIJI_HANJA[jijiIndex],
    ohaeng: {
      cheongan: CHEONGAN_OHAENG[cheongan],
      jiji: JIJI_OHAENG[jiji]
    }
  };
}

/**
 * 오행 상생상극 (Five Elements interaction) compatibility.
 * 상생 (generating): 목→화→토→금→수→목
 * 상극 (overcoming): 목→토→수→화→금→목
 */
const OHAENG_LIST = ['목', '화', '토', '금', '수'];

function getOhaengRelation(element1, element2) {
  if (element1 === element2) return 'same'; // 비화

  const idx1 = OHAENG_LIST.indexOf(element1);
  const idx2 = OHAENG_LIST.indexOf(element2);

  // 상생 check (generating cycle: each generates the next)
  if ((idx1 + 1) % 5 === idx2) return 'generate';   // element1 generates element2
  if ((idx2 + 1) % 5 === idx1) return 'generated';   // element1 is generated by element2

  // 상극 check (overcoming cycle: 목→토→수→화→금→목)
  const overcomeOrder = [0, 2, 4, 1, 3]; // 목→토→수→화→금
  const oi1 = overcomeOrder.indexOf(idx1);
  const oi2 = overcomeOrder.indexOf(idx2);
  if ((oi1 + 1) % 5 === oi2) return 'overcome';      // element1 overcomes element2
  if ((oi2 + 1) % 5 === oi1) return 'overcame';       // element1 is overcome by element2

  return 'neutral';
}

/**
 * Saju relationship evaluation.
 * Based on traditional 오행 상생상극 (Five Elements generating/overcoming) theory:
 * - 상생(相生): Elements that support and nurture each other
 * - 상극(相剋): Elements that control and challenge each other
 * - 비화(比和): Same elements that resonate together
 */
const SAJU_RELATIONSHIPS = {
  excellent: {
    label: '천생연분',
    description: '오행이 서로를 생(生)하는 상생 관계예요. 한쪽이 다른 쪽에게 자연스럽게 힘을 주고, 함께하면 서로의 기운이 더 좋아지는 조합입니다.'
  },
  great: {
    label: '아주 좋음',
    description: '오행의 흐름이 대체로 조화로운 관계예요. 서로의 기운이 잘 어울려 편안하고 자연스러운 만남이 될 수 있습니다.'
  },
  good: {
    label: '좋음',
    description: '비화(比和) — 같은 오행끼리의 공명이 있어요. 서로 비슷한 에너지를 가져 이해가 빠르고 공감대가 쉽게 형성됩니다.'
  },
  average: {
    label: '보통',
    description: '오행의 균형이 중립적인 관계예요. 특별한 충돌은 없지만, 서로에 대한 이해를 쌓아가면 더 좋아질 수 있는 관계입니다.'
  },
  challenging: {
    label: '도전적',
    description: '오행이 서로를 극(剋)하는 상극 관계가 포함되어 있어요. 강한 끌림이 있을 수 있지만, 서로의 차이를 존중하는 노력이 필요한 조합입니다.'
  }
};

export function getSajuEvalLabel(score) {
  if (score >= 90) return SAJU_RELATIONSHIPS.excellent.label;
  if (score >= 75) return SAJU_RELATIONSHIPS.great.label;
  if (score >= 65) return SAJU_RELATIONSHIPS.good.label;
  if (score >= 50) return SAJU_RELATIONSHIPS.average.label;
  return SAJU_RELATIONSHIPS.challenging.label;
}

export function getSajuRelationship(score) {
  if (score >= 90) return SAJU_RELATIONSHIPS.excellent.description;
  if (score >= 75) return SAJU_RELATIONSHIPS.great.description;
  if (score >= 65) return SAJU_RELATIONSHIPS.good.description;
  if (score >= 50) return SAJU_RELATIONSHIPS.average.description;
  return SAJU_RELATIONSHIPS.challenging.description;
}

export function formatIljuDisplay(ilju) {
  if (!ilju) return '';
  return `${ilju.cheongan}${ilju.jiji}(${ilju.cheonganHanja}${ilju.jijiHanja})`;
}

export function formatOhaengDisplay(ilju) {
  if (!ilju) return '';
  return `${OHAENG_NAMES[ilju.ohaeng.cheongan]}/${OHAENG_NAMES[ilju.ohaeng.jiji]}`;
}

/**
 * Calculate 일주 오행 궁합 score between two people.
 * Returns a score from 0 to 100.
 */
export function calculateIljuCompatibility(ilju1, ilju2) {
  const relations = [
    getOhaengRelation(ilju1.ohaeng.cheongan, ilju2.ohaeng.cheongan),
    getOhaengRelation(ilju1.ohaeng.jiji, ilju2.ohaeng.jiji),
    getOhaengRelation(ilju1.ohaeng.cheongan, ilju2.ohaeng.jiji),
    getOhaengRelation(ilju1.ohaeng.jiji, ilju2.ohaeng.cheongan),
  ];

  const scoreMap = {
    same: 70,
    generate: 100,
    generated: 90,
    overcome: 30,
    overcame: 40,
    neutral: 60
  };

  const totalScore = relations.reduce((sum, rel) => sum + scoreMap[rel], 0);
  return Math.round(totalScore / 4);
}
