/**
 * 일주(日柱) calculation - Heavenly Stem + Earthly Branch for a given date.
 * Based on the traditional Korean/Chinese 60-day Sexagenary cycle (육십갑자).
 */

// 천간 (Heavenly Stems)
export const CHEONGAN = ['갑', '을', '병', '정', '무', '기', '경', '신', '임', '계'];
export const CHEONGAN_HANJA = ['甲', '乙', '丙', '丁', '戊', '己', '庚', '辛', '壬', '癸'];

// 지지 (Earthly Branches)
export const JIJI = ['자', '축', '인', '묘', '진', '사', '오', '미', '신', '유', '술', '해'];
export const JIJI_HANJA = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];

// 오행 (Five Elements) mapping for 천간
export const CHEONGAN_OHAENG = {
  '갑': '목', '을': '목',
  '병': '화', '정': '화',
  '무': '토', '기': '토',
  '경': '금', '신': '금',
  '임': '수', '계': '수'
};

// 오행 mapping for 지지
export const JIJI_OHAENG = {
  '자': '수', '축': '토',
  '인': '목', '묘': '목',
  '진': '토', '사': '화',
  '오': '화', '미': '토',
  '신': '금', '유': '금',
  '술': '토', '해': '수'
};

/**
 * Calculate the 일주 (Day Pillar) from a solar date.
 * Reference date: January 1, 1900 was 갑자(甲子) day — index 0 in the 60-day cycle.
 * Actually, Jan 1 1900 = 경자(庚子). Let's use the known reference:
 * January 6, 1900 = 을사(乙巳) — well-documented reference point.
 *
 * More reliable: Jan 1, 2000 = 갑자(甲子) day? No.
 * Using well-known reference: 1900-01-01 = 庚子 (경자) day.
 * 庚 is index 6 in 천간, 子 is index 0 in 지지. sexagenary index = 36.
 */
const REFERENCE_DATE = new Date(Date.UTC(1900, 0, 1)); // 1900-01-01
const REFERENCE_CHEONGAN_INDEX = 6; // 경(庚)
const REFERENCE_JIJI_INDEX = 0;     // 자(子)

export function calculateIlju(year, month, day) {
  const targetDate = new Date(Date.UTC(year, month - 1, day));
  const diffTime = targetDate.getTime() - REFERENCE_DATE.getTime();
  const diffDays = Math.round(diffTime / (1000 * 60 * 60 * 24));

  const cheonganIndex = ((REFERENCE_CHEONGAN_INDEX + diffDays) % 10 + 10) % 10;
  const jijiIndex = ((REFERENCE_JIJI_INDEX + diffDays) % 12 + 12) % 12;

  return {
    cheongan: CHEONGAN[cheonganIndex],
    jiji: JIJI[jijiIndex],
    cheonganHanja: CHEONGAN_HANJA[cheonganIndex],
    jijiHanja: JIJI_HANJA[jijiIndex],
    ohaeng: {
      cheongan: CHEONGAN_OHAENG[CHEONGAN[cheonganIndex]],
      jiji: JIJI_OHAENG[JIJI[jijiIndex]]
    }
  };
}

/**
 * 오행 상생상극 (Five Elements interaction) compatibility.
 * 상생 (generating): 목→화→토→금→수→목
 * 상극 (overcoming): 목→토→수→화→금→목
 */
const OHAENG_LIST = ['목', '화', '토', '금', '수'];

function getOhaengRelation(element1, element2) {
  if (element1 === element2) return 'same'; // 비화

  const idx1 = OHAENG_LIST.indexOf(element1);
  const idx2 = OHAENG_LIST.indexOf(element2);

  // 상생 check (generating cycle: each generates the next)
  if ((idx1 + 1) % 5 === idx2) return 'generate';   // element1 generates element2
  if ((idx2 + 1) % 5 === idx1) return 'generated';   // element1 is generated by element2

  // 상극 check (overcoming cycle: 목→토→수→화→금→목)
  const overcomeOrder = [0, 2, 4, 1, 3]; // 목→토→수→화→금
  const oi1 = overcomeOrder.indexOf(idx1);
  const oi2 = overcomeOrder.indexOf(idx2);
  if ((oi1 + 1) % 5 === oi2) return 'overcome';      // element1 overcomes element2
  if ((oi2 + 1) % 5 === oi1) return 'overcame';       // element1 is overcome by element2

  return 'neutral';
}

/**
 * Calculate 일주 오행 궁합 score between two people.
 * Returns a score from 0 to 100.
 */
export function calculateIljuCompatibility(ilju1, ilju2) {
  const relations = [
    getOhaengRelation(ilju1.ohaeng.cheongan, ilju2.ohaeng.cheongan),
    getOhaengRelation(ilju1.ohaeng.jiji, ilju2.ohaeng.jiji),
    getOhaengRelation(ilju1.ohaeng.cheongan, ilju2.ohaeng.jiji),
    getOhaengRelation(ilju1.ohaeng.jiji, ilju2.ohaeng.cheongan),
  ];

  const scoreMap = {
    'same': 70,
    'generate': 100,
    'generated': 90,
    'overcome': 30,
    'overcame': 40,
    'neutral': 60
  };

  const totalScore = relations.reduce((sum, rel) => sum + scoreMap[rel], 0);
  return Math.round(totalScore / 4);
}
